### ISSUE TITLE
Crash when activating "grave event" tombstone

### ISSUE THREAD

**Issue by Xilef11** [Corail31/tombstone#1]
It seems to be caused by the spawning (and death) of the knight
[http://pastebin.com/TKdvvCXh](url)

**Comment by Corail31** [comment]
Sorry i'll check it :)
can you give me the good link? this one is broken.

**Comment by MrRiegel** [comment]
the link is correct. you have to copy the link manually

**Comment by Corail31** [comment]
I'll prevent the bug in the release1.2.2, Xilef11.
But it didn't succeed in reproducing the bug.
Don't hesitate to send me feedbacks about it on my curse profil :
[http://minecraft.curseforge.com/members/Corail31](http://minecraft.curseforge.com/members/Corail31)

**Comment by Xilef11** [comment]
looks fixed indeed
