### ISSUE TITLE
Request: Configurable time for decay

### ISSUE THREAD

**Issue by Divineaspect** [Corail31/tombstone#4]
In the interest of server play which may have large amounts of irregular players. I would like to request a configurable decay for the protection and need for keys to go away.

**Comment by Corail31** [comment]
A release is coming :
- it adds a config option with decayTime to be able to access the grave after x time
- the key vanish automatically when grave doesn't exist anymore (and if the holder of the key is in another dimension, the keys'll vanish when he'll return back to the dimension where the grave was)
